### ISSUE TITLE
Changes are not saved when editing custom sails / Black sails

### ISSUE THREAD

**Issue by LogiccccL** [zolantris/ValheimMods#16]
Certain options within the "Customize Sail" UI do not save and will revert back after a few seconds. For example, enabling "Allow raising sail" then hitting save will result in the sail rolling up as intended, but after a few seconds it will spring back down. When opening the UI again, the "Allow raising sail" option will be unchecked. However, other options (such as sail anchors) save just fine and remain saved indefinitely. In addition to this, sails will randomly turn completely black and remain that way until you relog/restart. 

I have tested this on a singleplayer world, with no other mods installed (other than the dependencies BepIn and Jotunn) and on the latest version of both Valheim and this plugin. 

Video showing both issues:
[https://streamable.com/uz3n6q](https://streamable.com/uz3n6q)

**Comment by zolantris** [comment]
Do you have any error logs to attach. Also are you using vortex, thunderstorm or manual install? 

Is the folder for the mod called ValheimRAFT or zolantris-ValheimRAFT?

**Comment by LogiccccL** [comment]
I am using r2modman. The folder is named "zolantris-ValheimRAFT". The output log within BepInEx for the session where I recreated the issue contains no errors. I will attach the output log incase I missed something.
[LogOutput.log](https://github.com/zolantris/ValheimRaft/files/13725291/LogOutput.log)

**Comment by zolantris** [comment]
The black sails issue is also not something I seen. Are you using vulkan by any chance?

**Comment by LogiccccL** [comment]
I don't think so, launching the game via r2modman skips the typical steam popup asking whether to launch with vulkan or not. If you know a way I can check once the game has launched I can check for you.

**Comment by zolantris** [comment]
Typically you can find that in the player logs. https://steamcommunity.com/app/892970/discussions/1/4263206669438586409/

**Comment by zolantris** [comment]
Example for me on dx11 I see this log when launching the client.

```
[Physics::Module] Initialized MultithreadedJobDispatcher with 19 workers.
Initialize engine version: 2022.3.12f1 (4fe6e059c7ef)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/Valheim/valheim_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=0
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 3090 Ti (ID=0x2203)
    Vendor:   NVIDIA
    VRAM:     24327 MB
    Driver:   31.0.15.4629
Begin MonoManager ReloadAssembly
- Loaded All Assemblies, in  0.052 seconds
- Finished resetting the current domain, in  0.001 seconds
<RI> Initializing input.
```

**Comment by LogiccccL** [comment]
It appears I am running on dx11 as well
```
[Physics::Module] Initialized MultithreadedJobDispatcher with 15 workers.
Initialize engine version: 2022.3.12f1 (4fe6e059c7ef)
[Subsystems] Discovering subsystems at path D:/Programs/Steam/steamapps/common/Valheim/valheim_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=0
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 3060 Ti (ID=0x2489)
    Vendor:   NVIDIA
    VRAM:     8038 MB
    Driver:   31.0.15.3623
Begin MonoManager ReloadAssembly
- Loaded All Assemblies, in  0.086 seconds
- Finished resetting the current domain, in  0.001 seconds
<RI> Initializing input.
```
